import {createPublicClient,http,parseAbiItem,decodeFunctionResult,encodeFunctionData,formatEther,formatUnits} from 'viem';
import {robinhoodTestnet,CONTRACTS,DEPLOY_BLOCK,CHUNK} from './config';
import {factoryAbi,curveAbi,tokenAbi,multicallAbi} from './abis';
export const publicClient=createPublicClient({chain:robinhoodTestnet,transport:http(robinhoodTestnet.rpcUrls.default.http[0])});
export type TokenInfo={token:`0x${string}`;curve:`0x${string}`;deployer:`0x${string}`;pairToken:`0x${string}`;name:string;symbol:string;logo:string;quoteReserve:bigint;tokenReserve:bigint;realQuoteReserve:bigint;graduationThreshold:bigint;feeBps:bigint;creatorTaxBps:bigint;phase:number;price:string;progressBps:bigint};
const launchedEvent=parseAbiItem('event TokenLaunched(address indexed token,address indexed curve,address indexed deployer,address pairToken,uint256 launchConfigId,uint256 graduationThreshold)');
export async function scanTokens(){const latest=await publicClient.getBlockNumber(); const out=new Map<string,{token:`0x${string}`,curve:`0x${string}`,deployer:`0x${string}`,pairToken:`0x${string}`}>(); for(let from=BigInt(DEPLOY_BLOCK);from<=latest;from+=BigInt(CHUNK)){const to=from+BigInt(CHUNK)-1n>latest?latest:from+BigInt(CHUNK)-1n; const logs=await publicClient.getLogs({address:CONTRACTS.factory,event:launchedEvent,fromBlock:from,toBlock:to}); for(const l of logs){const a=l.args; if(a.token&&a.curve) out.set(a.token.toLowerCase(),{token:a.token,curve:a.curve,deployer:a.deployer!,pairToken:a.pairToken!});}} return [...out.values()];}
export async function loadTokens(){const raw=await scanTokens(); if(!raw.length)return []; const calls=raw.flatMap(t=>[...(['name','symbol','logo'] as const).map(fn=>({target:t.token,allowFailure:true,callData:encodeFunctionData({abi:tokenAbi,functionName:fn})})), ...(['getReserves','realQuoteReserve','graduationThreshold','feeBps','creatorTaxBps'] as const).map(fn=>({target:t.curve,allowFailure:true,callData:encodeFunctionData({abi:curveAbi,functionName:fn})})), {target:CONTRACTS.factory,allowFailure:true,callData:encodeFunctionData({abi:factoryAbi,functionName:'getLaunchedToken',args:[t.token]})}]); const res=await publicClient.readContract({address:CONTRACTS.multicall3,abi:multicallAbi,functionName:'aggregate3',args:[calls]}); let i=0; const decoded:any[]=[]; for(const r of res){decoded.push(r.success?r.returnData:null); i++;} const list:TokenInfo[]=[]; let k=0; for(const t of raw){const name=decoded[k] ? decodeFunctionResult({abi:tokenAbi,functionName:'name',data:decoded[k++]}) as string : 'Unknown'; const symbol=decoded[k] ? decodeFunctionResult({abi:tokenAbi,functionName:'symbol',data:decoded[k++]}) as string : 'TOKEN'; const logo=decoded[k] ? decodeFunctionResult({abi:tokenAbi,functionName:'logo',data:decoded[k++]}) as string : ''; const rr=decoded[k++] ? decodeFunctionResult({abi:curveAbi,functionName:'getReserves',data:decoded[k-1]}) as readonly [bigint,bigint] : [0n,0n]; const real=decoded[k++] ? decodeFunctionResult({abi:curveAbi,functionName:'realQuoteReserve',data:decoded[k-1]}) as bigint : 0n; const threshold=decoded[k++] ? decodeFunctionResult({abi:curveAbi,functionName:'graduationThreshold',data:decoded[k-1]}) as bigint : 0n; const fee=decoded[k++] ? decodeFunctionResult({abi:curveAbi,functionName:'feeBps',data:decoded[k-1]}) as bigint : 0n; const tax=decoded[k++] ? decodeFunctionResult({abi:curveAbi,functionName:'creatorTaxBps',data:decoded[k-1]}) as bigint : 0n; const launched=decoded[k++] ? decodeFunctionResult({abi:factoryAbi,functionName:'getLaunchedToken',data:decoded[k-1]}) as any : null; const phase=launched?.phase??0; const progressBps=threshold? (real*10000n/threshold>10000n?10000n:real*10000n/threshold):0n; list.push({...t,name,symbol,logo,quoteReserve:rr[0],tokenReserve:rr[1],realQuoteReserve:real,graduationThreshold:threshold,feeBps:fee,creatorTaxBps:tax,phase:Number(phase),price:rr[1]?formatEther(rr[0]*10n**18n/rr[1]):'0',progressBps}); } return list;}
export function estimate(quoteIn:bigint,t:TokenInfo){if(quoteIn<=0n||t.quoteReserve<=0n||t.tokenReserve<=0n)return {tokensOut:0n,minTokensOut:0n}; const fee=quoteIn*t.feeBps/10000n,tax=quoteIn*t.creatorTaxBps/10000n,net=quoteIn-fee-tax; const tokensOut=net*t.tokenReserve/(t.quoteReserve+net); return {tokensOut,minTokensOut:tokensOut};}
export const fmtEth=(v:bigint)=>Number(formatEther(v))<0.000001?formatEther(v):Number(formatEther(v)).toFixed(6).replace(/0+$/,'').replace(/\.$/,'');
export const fmtToken=(v:bigint)=>formatUnits(v,18);
